micronaut.application.name=netlog
## datasources.default.schema-generate=CREATE
datasources.default.password=
datasources.default.username=sa
datasources.default.url=jdbc:sqlite:${NETLOG_DATABASE_FILE:D:/ham/netlog.db}
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.dialect=H2
datasources.default.hikari.maximum-pool-size=1
datasources.default.hikari.minimum-idle=0
micronaut.server.port=${NETLOG_HTTP_PORT:8701}
micronaut.data.jdbc.connection.read-only=false
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
